-- MySQL Script generated by MySQL Workbench
-- Wed Dec 13 08:42:16 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pessoa` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(240) NOT NULL,
  `tipo` ENUM('F', 'J') NOT NULL,
  `categoria` ENUM('1', '2', '3', '4', '5', '99') NOT NULL COMMENT '1-Colaborador\n2-Parceiros\n3-Empresa\n4-Cooperativa\n5-Vendedor\n99-Não identificada',
  `cpf_cnpj` VARCHAR(14) NOT NULL,
  UNIQUE INDEX `idPessoa_UNIQUE` (`id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `cpf_cnpj_UNIQUE` (`cpf_cnpj` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PessoaFisica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PessoaFisica` (
  `Pessoa_id` INT NOT NULL,
  `numeroReservista` VARCHAR(64) NULL,
  `dataNascimento` DATE NOT NULL,
  PRIMARY KEY (`Pessoa_id`),
  CONSTRAINT `fk_PessoaFisica_Pessoa`
    FOREIGN KEY (`Pessoa_id`)
    REFERENCES `mydb`.`Pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pais` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Estado` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(60) NOT NULL,
  `Pais_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Estado_Pais1_idx` (`Pais_id` ASC) VISIBLE,
  CONSTRAINT `fk_Estado_Pais1`
    FOREIGN KEY (`Pais_id`)
    REFERENCES `mydb`.`Pais` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cidade` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Estado_id` INT NOT NULL,
  `nome` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Cidade_Estado1_idx` (`Estado_id` ASC) VISIBLE,
  CONSTRAINT `fk_Cidade_Estado10`
    FOREIGN KEY (`Estado_id`)
    REFERENCES `mydb`.`Estado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Endereco` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Cidade_id` INT NOT NULL,
  `tipo` ENUM('Rua', 'Avenida', 'Rodovia', 'Praca') NULL,
  `logradouro` VARCHAR(160) NOT NULL,
  `CEP` VARCHAR(8) NULL,
  `Bairro` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Endereco_Cidade1_idx` (`Cidade_id` ASC) VISIBLE,
  CONSTRAINT `fk_Endereco_Cidade1`
    FOREIGN KEY (`Cidade_id`)
    REFERENCES `mydb`.`Cidade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PessoaEndereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PessoaEndereco` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Pessoa_id` INT NOT NULL,
  `Endereco_id` INT NOT NULL,
  `tipo` ENUM('1', '2', '3', '4') NOT NULL,
  `status` ENUM('0', '1') NOT NULL COMMENT 'Os status podem ser:\n0- Inativo (quando for excluido na aplicação)\n1- Ativo',
  `numero` VARCHAR(12) NOT NULL,
  `complemento` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_PessoaEndereco_Pessoa1_idx` (`Pessoa_id` ASC) VISIBLE,
  INDEX `fk_PessoaEndereco_Endereco1_idx` (`Endereco_id` ASC) VISIBLE,
  CONSTRAINT `fk_PessoaEndereco_Pessoa1`
    FOREIGN KEY (`Pessoa_id`)
    REFERENCES `mydb`.`Pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PessoaEndereco_Endereco1`
    FOREIGN KEY (`Endereco_id`)
    REFERENCES `mydb`.`Endereco` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`departamento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `sigla` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC) VISIBLE,
  UNIQUE INDEX `sigla_UNIQUE` (`sigla` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PessoaDepartamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PessoaDepartamento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `dataAdmissao` DATE NOT NULL,
  `departamento_id` INT NOT NULL,
  `Pessoa_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_PessoaDepartamento_departamento1_idx` (`departamento_id` ASC) VISIBLE,
  INDEX `fk_PessoaDepartamento_Pessoa1_idx` (`Pessoa_id` ASC) VISIBLE,
  CONSTRAINT `fk_PessoaDepartamento_departamento1`
    FOREIGN KEY (`departamento_id`)
    REFERENCES `mydb`.`departamento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PessoaDepartamento_Pessoa1`
    FOREIGN KEY (`Pessoa_id`)
    REFERENCES `mydb`.`Pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PessoaVinculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PessoaVinculo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo` ENUM('1', '2', '3') NOT NULL COMMENT '1-Dependente\n2-Filia\n3-Representante',
  `Pessoa_id_Principal` INT NOT NULL,
  `Pessoa_id1_Vinculo` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_PessoaVinculo_Pessoa1_idx` (`Pessoa_id_Principal` ASC) VISIBLE,
  INDEX `fk_PessoaVinculo_Pessoa2_idx` (`Pessoa_id1_Vinculo` ASC) VISIBLE,
  CONSTRAINT `fk_PessoaVinculo_Pessoa1`
    FOREIGN KEY (`Pessoa_id_Principal`)
    REFERENCES `mydb`.`Pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PessoaVinculo_Pessoa2`
    FOREIGN KEY (`Pessoa_id1_Vinculo`)
    REFERENCES `mydb`.`Pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pessoaRegiaoAtuacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pessoaRegiaoAtuacao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `percentualComissao` DECIMAL(5,2) NOT NULL,
  `viajante` ENUM('1', '2', '3', '4', '5') NOT NULL COMMENT '1- Regional\n2- Nacional\n3- Não viajante\n4- Internacional\n5- Sem limitação',
  `Pessoa_id` INT NOT NULL,
  `Estado_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pessoaRegiaoAtuacao_Pessoa1_idx` (`Pessoa_id` ASC) VISIBLE,
  INDEX `fk_pessoaRegiaoAtuacao_Estado1_idx` (`Estado_id` ASC) VISIBLE,
  CONSTRAINT `fk_pessoaRegiaoAtuacao_Pessoa1`
    FOREIGN KEY (`Pessoa_id`)
    REFERENCES `mydb`.`Pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pessoaRegiaoAtuacao_Estado1`
    FOREIGN KEY (`Estado_id`)
    REFERENCES `mydb`.`Estado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP);


-- -----------------------------------------------------
-- Table `mydb`.`timestamps`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`timestamps` (
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL);


-- -----------------------------------------------------
-- Table `mydb`.`Peca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Peca` (
  `codigoPeca` INT NOT NULL,
  `descricao` VARCHAR(255) NOT NULL,
  `cor` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`codigoPeca`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Projeto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Projeto` (
  `codigoProjeto` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(255) NOT NULL,
  `nomeCoordenador` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`codigoProjeto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PecaProjeto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PecaProjeto` (
  `Peca_codigoPeca` INT NOT NULL,
  `Projeto_codigoProjeto` INT NOT NULL,
  `preco` DECIMAL(10,2) NOT NULL,
  `tamanho` VARCHAR(45) NULL,
  PRIMARY KEY (`Peca_codigoPeca`, `Projeto_codigoProjeto`),
  INDEX `fk_PecaProjeto_Projeto1_idx` (`Projeto_codigoProjeto` ASC) VISIBLE,
  CONSTRAINT `fk_PecaProjeto_Peca1`
    FOREIGN KEY (`Peca_codigoPeca`)
    REFERENCES `mydb`.`Peca` (`codigoPeca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PecaProjeto_Projeto1`
    FOREIGN KEY (`Projeto_codigoProjeto`)
    REFERENCES `mydb`.`Projeto` (`codigoProjeto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pessoa1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pessoa1` (
  `ID` INT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(240) NOT NULL,
  `Tipo` ENUM('F', 'J') NOT NULL COMMENT 'F - físico\nJ - Jurídico',
  `Categoria` ENUM('1', '2', '3', '4', '5', '99') NOT NULL COMMENT 'São categorias de pessoas\n\n1 - Funcionários\n2 - Parceiros \n3 - Empresas\n4 - Cooperativa\n5 - Vendedor\n99 - Non ID',
  `CPF_CNPJ` VARCHAR(14) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  UNIQUE INDEX `CPF_CNPJ_UNIQUE` (`CPF_CNPJ` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pessoa_fisica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pessoa_fisica` (
  `NºReservista` VARCHAR(60) NOT NULL,
  `DataNascimento` DATE NULL,
  `Pessoa_ID` INT NOT NULL,
  PRIMARY KEY (`Pessoa_ID`),
  CONSTRAINT `fk_Pessoa física_Pessoa`
    FOREIGN KEY (`Pessoa_ID`)
    REFERENCES `mydb`.`Pessoa1` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pais1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pais1` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nome_Pais` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `Nome_UNIQUE` (`Nome_Pais` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Estado1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Estado1` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nome_Estado` VARCHAR(45) NOT NULL,
  `Pais_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `NomeEstado_UNIQUE` (`Nome_Estado` ASC) VISIBLE,
  INDEX `fk_Estado_Pais1_idx` (`Pais_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Estado_Pais1`
    FOREIGN KEY (`Pais_ID`)
    REFERENCES `mydb`.`Pais1` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Endereco1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Endereco1` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Tipo` ENUM('Rua', 'Avenida', 'Rodovia', 'Praça') NOT NULL,
  `Logradouro` VARCHAR(160) NOT NULL,
  `CEP` VARCHAR(8) NOT NULL,
  `Bairro` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
KEY_BLOCK_SIZE = 1;


-- -----------------------------------------------------
-- Table `mydb`.`Cidade1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cidade1` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nome_Cidade` VARCHAR(120) NOT NULL,
  `Estado_ID` INT NOT NULL,
  `Endereco_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Cidade_Estado1_idx` (`Estado_ID` ASC) VISIBLE,
  INDEX `fk_Cidade_Endereco1_idx` (`Endereco_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Cidade_Estado1`
    FOREIGN KEY (`Estado_ID`)
    REFERENCES `mydb`.`Estado1` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cidade_Endereco1`
    FOREIGN KEY (`Endereco_ID`)
    REFERENCES `mydb`.`Endereco1` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PessoaEndereco1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PessoaEndereco1` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Tipo` ENUM('1', '2', '3', '4') NOT NULL COMMENT 'Os tipos de enderelis podem ser:\n\n1 - Residência\n2 - Trabalho\n3 - Cobrança\n4 - Entregas',
  `Status` ENUM('0', '1') NOT NULL COMMENT 'Status são:\n\n0 - Inativo\n1 - Ativo',
  `Numero` VARCHAR(10) NOT NULL,
  `Complemento` VARCHAR(120) NULL,
  `Endereco_ID` INT NOT NULL,
  `Pessoa_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_PessoaEndereco_Endereco1_idx` (`Endereco_ID` ASC) VISIBLE,
  INDEX `fk_PessoaEndereco_Pessoa1_idx` (`Pessoa_ID` ASC) VISIBLE,
  CONSTRAINT `fk_PessoaEndereco_Endereco1`
    FOREIGN KEY (`Endereco_ID`)
    REFERENCES `mydb`.`Endereco1` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PessoaEndereco_Pessoa1`
    FOREIGN KEY (`Pessoa_ID`)
    REFERENCES `mydb`.`Pessoa1` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Departamento1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Departamento1` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `Sigla` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `Nome_UNIQUE` (`Nome` ASC) VISIBLE,
  UNIQUE INDEX `Sigla_UNIQUE` (`Sigla` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PessoaDepartamento1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PessoaDepartamento1` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `DataAdmissao` DATE NOT NULL,
  `Departamento_ID` INT NOT NULL,
  `Pessoa_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_PessoaDepartamento_Departamento1_idx` (`Departamento_ID` ASC) VISIBLE,
  INDEX `fk_PessoaDepartamento_Pessoa1_idx` (`Pessoa_ID` ASC) VISIBLE,
  CONSTRAINT `fk_PessoaDepartamento_Departamento1`
    FOREIGN KEY (`Departamento_ID`)
    REFERENCES `mydb`.`Departamento1` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PessoaDepartamento_Pessoa1`
    FOREIGN KEY (`Pessoa_ID`)
    REFERENCES `mydb`.`Pessoa1` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PessoaVinculo1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PessoaVinculo1` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Tipo` ENUM('1', '2', '3') NOT NULL COMMENT '1 - Dependente\n2 - filial\n3 - Representante ',
  `Pessoa_ID_Principal` INT NOT NULL,
  `Pessoa_ID_Vinculo` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_PessoaVinculo_Pessoa1_idx` (`Pessoa_ID_Principal` ASC) VISIBLE,
  INDEX `fk_PessoaVinculo_Pessoa2_idx` (`Pessoa_ID_Vinculo` ASC) VISIBLE,
  CONSTRAINT `fk_PessoaVinculo_Pessoa1`
    FOREIGN KEY (`Pessoa_ID_Principal`)
    REFERENCES `mydb`.`Pessoa1` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PessoaVinculo_Pessoa2`
    FOREIGN KEY (`Pessoa_ID_Vinculo`)
    REFERENCES `mydb`.`Pessoa1` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PessoaAreaAtuacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PessoaAreaAtuacao` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `ComissaoPercentual` DECIMAL(5,2) NOT NULL,
  `Viajante` ENUM('1', '2', '3', '4', '5') NOT NULL COMMENT '1 - Regional\n2 - Nacional\n3 - Não Viajante\n4 - Internacional\n5 - Miserável',
  `Pessoa_ID` INT NOT NULL,
  `Estado_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_PessoaAreaAtuacao_Pessoa1_idx` (`Pessoa_ID` ASC) VISIBLE,
  INDEX `fk_PessoaAreaAtuacao_Estado1_idx` (`Estado_ID` ASC) VISIBLE,
  CONSTRAINT `fk_PessoaAreaAtuacao_Pessoa1`
    FOREIGN KEY (`Pessoa_ID`)
    REFERENCES `mydb`.`Pessoa1` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PessoaAreaAtuacao_Estado1`
    FOREIGN KEY (`Estado_ID`)
    REFERENCES `mydb`.`Estado1` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Material`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Material` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nome_Material` VARCHAR(100) NOT NULL,
  `Classe_Material` ENUM('1', '2', '3', '4', '5') NOT NULL COMMENT '1 - Refinado\n2 - Bruto\n3 - Em transição\n4 - Degradado\n5 - Estado padrão',
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Destino`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Destino` (
  `ID` INT NOT NULL,
  `Tipo` ENUM('1', '2', '3') NOT NULL COMMENT '1 - Obra governo\n2 - Obra Privada\n3 - Mineradora\n',
  `Logradouro` VARCHAR(160) NOT NULL,
  `CEP` VARCHAR(8) NOT NULL,
  `Bairro` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Transporte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Transporte` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nome_Motorista` VARCHAR(100) NOT NULL,
  `Placa_Caminhao` INT NOT NULL,
  `Tipo_Transporte` ENUM('1', '2') NOT NULL COMMENT '1 - Entrada\n2 - Saída\n',
  `Data_Hora` DATE NOT NULL,
  `Peso_Material` FLOAT NOT NULL,
  `Destino_ID` INT NOT NULL,
  `Material_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Transporte_Destino1_idx` (`Destino_ID` ASC) VISIBLE,
  INDEX `fk_Transporte_Material1_idx` (`Material_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Transporte_Destino1`
    FOREIGN KEY (`Destino_ID`)
    REFERENCES `mydb`.`Destino` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Transporte_Material1`
    FOREIGN KEY (`Material_ID`)
    REFERENCES `mydb`.`Material` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pais2`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pais2` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nome_Pais` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Estado2`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Estado2` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nome_estado` VARCHAR(45) NOT NULL,
  `Pais_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Estado_Pais2_idx` (`Pais_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Estado_Pais2`
    FOREIGN KEY (`Pais_ID`)
    REFERENCES `mydb`.`Pais2` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cidade2`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cidade2` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nome_cidade` VARCHAR(45) NOT NULL,
  `Estado_ID` INT NOT NULL,
  `Destino_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Cidade_Estado2_idx` (`Estado_ID` ASC) VISIBLE,
  INDEX `fk_Cidade_Destino1_idx` (`Destino_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Cidade_Estado2`
    FOREIGN KEY (`Estado_ID`)
    REFERENCES `mydb`.`Estado2` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cidade_Destino1`
    FOREIGN KEY (`Destino_ID`)
    REFERENCES `mydb`.`Destino` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pessoa2`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pessoa2` (
  `ID` INT NULL AUTO_INCREMENT,
  `Nome_Pessoa` VARCHAR(240) NOT NULL,
  `Categoria` ENUM('1', '2', '3', '99') NOT NULL COMMENT 'São categorias de pessoas\n\n1 - Astro Cinema\n2 - Funcionário \n3 - Cliente\n99 - Non ID',
  `Contato` VARCHAR(60) NOT NULL,
  `Codigo_Associado` VARCHAR(60) NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  UNIQUE INDEX `Contato_UNIQUE` (`Contato` ASC) VISIBLE,
  UNIQUE INDEX `Codigo_Associado_UNIQUE` (`Codigo_Associado` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pais3`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pais3` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nome_Pais` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `Nome_UNIQUE` (`Nome_Pais` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Estado3`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Estado3` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nome_Estado` VARCHAR(45) NOT NULL,
  `Pais_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `NomeEstado_UNIQUE` (`Nome_Estado` ASC) VISIBLE,
  INDEX `fk_Estado_Pais1_idx` (`Pais_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Estado_Pais10`
    FOREIGN KEY (`Pais_ID`)
    REFERENCES `mydb`.`Pais3` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Endereco2`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Endereco2` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Tipo` ENUM('Rua', 'Avenida', 'Rodovia', 'Praça') NOT NULL,
  `Logradouro` VARCHAR(160) NOT NULL,
  `CEP` VARCHAR(8) NOT NULL,
  `Bairro` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
KEY_BLOCK_SIZE = 1;


-- -----------------------------------------------------
-- Table `mydb`.`Cidade3`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cidade3` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nome_Cidade` VARCHAR(120) NOT NULL,
  `Estado_ID` INT NOT NULL,
  `Endereco_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Cidade_Estado1_idx` (`Estado_ID` ASC) VISIBLE,
  INDEX `fk_Cidade_Endereco1_idx` (`Endereco_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Cidade_Estado10`
    FOREIGN KEY (`Estado_ID`)
    REFERENCES `mydb`.`Estado3` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cidade_Endereco10`
    FOREIGN KEY (`Endereco_ID`)
    REFERENCES `mydb`.`Endereco2` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pessoa_Endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pessoa_Endereco` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Tipo` ENUM('1', '2', '3', '4') NOT NULL COMMENT 'Os tipos de enderelis podem ser:\n\n1 - Residência\n2 - Trabalho\n3 - Cobrança\n4 - Entregas',
  `Status` ENUM('0', '1') NOT NULL COMMENT 'Status são:\n\n0 - Inativo\n1 - Ativo',
  `Numero` VARCHAR(10) NOT NULL,
  `Complemento` VARCHAR(120) NULL,
  `Endereco_ID` INT NOT NULL,
  `Pessoa_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_PessoaEndereco_Endereco1_idx` (`Endereco_ID` ASC) VISIBLE,
  INDEX `fk_PessoaEndereco_Pessoa1_idx` (`Pessoa_ID` ASC) VISIBLE,
  CONSTRAINT `fk_PessoaEndereco_Endereco10`
    FOREIGN KEY (`Endereco_ID`)
    REFERENCES `mydb`.`Endereco2` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PessoaEndereco_Pessoa10`
    FOREIGN KEY (`Pessoa_ID`)
    REFERENCES `mydb`.`Pessoa2` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Conteudo_AudioVideo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Conteudo_AudioVideo` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Tipo_Conteudo` ENUM('1', '2', '3') NOT NULL COMMENT '1 - Filme\n2 - Documentário\n3 - Série\n',
  `Codigo_Conteudo` VARCHAR(45) NOT NULL,
  `Categoria_Conteudo` ENUM('1', '2', '3', '4', '5') NOT NULL COMMENT '1 - Comédia\n2 - Suspense\n3 - Drama\n4 - Romance\n5 - Terror',
  `Copias_Disponiveis` INT NOT NULL,
  `Titulo_Conteudo` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `Codigo_Conteudo_UNIQUE` (`Codigo_Conteudo` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Copias_Conteudo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Copias_Conteudo` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Conteudo_Video_ID` INT NOT NULL,
  `Disponibilidade_Copia` TINYINT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Copias_Conteudo_Conteudo_Video1_idx` (`Conteudo_Video_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Copias_Conteudo_Conteudo_Video1`
    FOREIGN KEY (`Conteudo_Video_ID`)
    REFERENCES `mydb`.`Conteudo_AudioVideo` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Aluguel_Conteudo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Aluguel_Conteudo` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Copias_Conteudo_ID` INT NOT NULL,
  `Pessoa_ID` INT NOT NULL,
  `Data_Aluguel` DATE NOT NULL,
  `Data_Devolucao` DATE NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Aluguel_Conteudo_Copias_Conteudo1_idx` (`Copias_Conteudo_ID` ASC) VISIBLE,
  INDEX `fk_Aluguel_Conteudo_Pessoa1_idx` (`Pessoa_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Aluguel_Conteudo_Copias_Conteudo1`
    FOREIGN KEY (`Copias_Conteudo_ID`)
    REFERENCES `mydb`.`Copias_Conteudo` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Aluguel_Conteudo_Pessoa1`
    FOREIGN KEY (`Pessoa_ID`)
    REFERENCES `mydb`.`Pessoa2` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pessoa3`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pessoa3` (
  `id` INT NULL AUTO_INCREMENT,
  `nome` VARCHAR(180) NOT NULL,
  `tipo` ENUM('F', 'J') NOT NULL COMMENT 'Tipo da pessoa pode ser:\nF- Físico\nJ-Juridico',
  `categoria` ENUM('1', '2', '3', '4', '5', '99') NOT NULL COMMENT 'São categorias de pessoas:\n1-Colaborador\n2-Parceiros\n3-Empresa\n4-Cooperativa\n5-Vendedor\n99-Não identificada',
  `cpf_cnpj` VARCHAR(14) NOT NULL COMMENT 'Para formatar o campo, verifique o tipo da pessoa',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `cpf_cnpj_UNIQUE` (`cpf_cnpj` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pessoaFisica1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pessoaFisica1` (
  `Pessoa_id` INT NOT NULL,
  `numeroReservista` VARCHAR(64) NULL,
  `dataNascimento` DATE NULL,
  PRIMARY KEY (`Pessoa_id`),
  CONSTRAINT `fk_pessoaFisica_Pessoa`
    FOREIGN KEY (`Pessoa_id`)
    REFERENCES `mydb`.`Pessoa3` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pais4`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pais4` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`estado4`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`estado4` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(60) NOT NULL,
  `pais_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC) VISIBLE,
  INDEX `fk_estado_pais1_idx` (`pais_id` ASC) VISIBLE,
  CONSTRAINT `fk_estado_pais1`
    FOREIGN KEY (`pais_id`)
    REFERENCES `mydb`.`pais4` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cidade4`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cidade4` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(120) NOT NULL,
  `estado_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cidade_estado1_idx` (`estado_id` ASC) VISIBLE,
  CONSTRAINT `fk_cidade_estado1`
    FOREIGN KEY (`estado_id`)
    REFERENCES `mydb`.`estado4` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`endereco3`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`endereco3` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo` ENUM('Rua', 'Avenida', 'Rodovia', 'Praça') NOT NULL,
  `logradouro` VARCHAR(160) NOT NULL,
  `CEP` VARCHAR(8) NOT NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `cidade_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_endereco_cidade1_idx` (`cidade_id` ASC) VISIBLE,
  CONSTRAINT `fk_endereco_cidade1`
    FOREIGN KEY (`cidade_id`)
    REFERENCES `mydb`.`cidade4` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pessoaEndereco2`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pessoaEndereco2` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo` ENUM('1', '2', '3', '4') NOT NULL COMMENT 'Os tipos de endereços pode ser:\n\n1- Residencia\n2- Trabalho\n3- Cobrança\n4- Entregas',
  `status` ENUM('0', '1') NOT NULL COMMENT 'Os statuts pode ser:\n\n0-Inativo (quando for excluidos na aplicação)\n1-Ativo',
  `numero` VARCHAR(10) NOT NULL,
  `complemento` VARCHAR(45) NOT NULL,
  `Pessoa_id` INT NOT NULL,
  `endereco_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pessoaEndereco_Pessoa1_idx` (`Pessoa_id` ASC) VISIBLE,
  INDEX `fk_pessoaEndereco_endereco1_idx` (`endereco_id` ASC) VISIBLE,
  CONSTRAINT `fk_pessoaEndereco_Pessoa1`
    FOREIGN KEY (`Pessoa_id`)
    REFERENCES `mydb`.`Pessoa3` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pessoaEndereco_endereco1`
    FOREIGN KEY (`endereco_id`)
    REFERENCES `mydb`.`endereco3` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`departamento2`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`departamento2` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `sigla` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pessoaDepartamento2`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pessoaDepartamento2` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `DataAdimissao` DATE NULL,
  `departamento_id` INT NOT NULL,
  `Pessoa_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pessoaDepartamento_departamento1_idx` (`departamento_id` ASC) VISIBLE,
  INDEX `fk_pessoaDepartamento_Pessoa1_idx` (`Pessoa_id` ASC) VISIBLE,
  CONSTRAINT `fk_pessoaDepartamento_departamento1`
    FOREIGN KEY (`departamento_id`)
    REFERENCES `mydb`.`departamento2` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pessoaDepartamento_Pessoa1`
    FOREIGN KEY (`Pessoa_id`)
    REFERENCES `mydb`.`Pessoa3` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pessoaVinculo2`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pessoaVinculo2` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pessoaVinculo` ENUM('1', '2', '3') NULL COMMENT '1-Dependente\n2-Filial\n3-Representante',
  `Pessoa_id_Principal` INT NOT NULL,
  `Pessoa_id1_Vinculo` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pessoaVinculo_Pessoa1_idx` (`Pessoa_id_Principal` ASC) VISIBLE,
  INDEX `fk_pessoaVinculo_Pessoa2_idx` (`Pessoa_id1_Vinculo` ASC) VISIBLE,
  CONSTRAINT `fk_pessoaVinculo_Pessoa1`
    FOREIGN KEY (`Pessoa_id_Principal`)
    REFERENCES `mydb`.`Pessoa3` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pessoaVinculo_Pessoa2`
    FOREIGN KEY (`Pessoa_id1_Vinculo`)
    REFERENCES `mydb`.`Pessoa3` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pessoaRegiaoAtuacao1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pessoaRegiaoAtuacao1` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `percentualComossao` DECIMAL(5,2) NOT NULL,
  `viajante` ENUM('1', '2', '3', '4', '5') NULL COMMENT 'São tipos de viajantes:\n\n1-Regional\n2-Nacional\n3-Não Viajante\n4-Internacional\n5-Ilimitado',
  `Pessoa_id` INT NOT NULL,
  `estado_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pessoaRegiaoAtuacao_Pessoa1_idx` (`Pessoa_id` ASC) VISIBLE,
  INDEX `fk_pessoaRegiaoAtuacao_estado1_idx` (`estado_id` ASC) VISIBLE,
  CONSTRAINT `fk_pessoaRegiaoAtuacao_Pessoa1`
    FOREIGN KEY (`Pessoa_id`)
    REFERENCES `mydb`.`Pessoa3` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pessoaRegiaoAtuacao_estado1`
    FOREIGN KEY (`estado_id`)
    REFERENCES `mydb`.`estado4` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`materiaPrima`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`materiaPrima` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Material` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pessoa4`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pessoa4` (
  `id` INT NULL AUTO_INCREMENT,
  `nome` VARCHAR(180) NOT NULL,
  `cpf_cnpj` VARCHAR(14) NOT NULL COMMENT 'Para formatar o campo, verifique o tipo da pessoa',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `cpf_cnpj_UNIQUE` (`cpf_cnpj` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pais5`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pais5` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`estado5`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`estado5` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(60) NOT NULL,
  `pais_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC) VISIBLE,
  INDEX `fk_estado_pais1_idx` (`pais_id` ASC) VISIBLE,
  CONSTRAINT `fk_estado_pais10`
    FOREIGN KEY (`pais_id`)
    REFERENCES `mydb`.`pais5` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cidade5`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cidade5` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(120) NOT NULL,
  `estado_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cidade_estado1_idx` (`estado_id` ASC) VISIBLE,
  CONSTRAINT `fk_cidade_estado10`
    FOREIGN KEY (`estado_id`)
    REFERENCES `mydb`.`estado5` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`endereco4`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`endereco4` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo` ENUM('Rua', 'Avenida', 'Rodovia', 'Praça') NOT NULL,
  `logradouro` VARCHAR(160) NOT NULL,
  `CEP` VARCHAR(8) NOT NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `cidade_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_endereco_cidade1_idx` (`cidade_id` ASC) VISIBLE,
  CONSTRAINT `fk_endereco_cidade10`
    FOREIGN KEY (`cidade_id`)
    REFERENCES `mydb`.`cidade5` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Veiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Veiculo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo` ENUM('1', '2', '3') NOT NULL COMMENT '1-Carro\n2-Moto\n3-Caminhão',
  `placa` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `placa_UNIQUE` (`placa` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`registroViagens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`registroViagens` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data_e_Horario_Saida` DATETIME NOT NULL,
  `data_e_Horario_Entrada` DATETIME NOT NULL,
  `peso_Entrada` FLOAT NOT NULL,
  `peso_Saida` FLOAT NOT NULL,
  `quantidade_Material` FLOAT NOT NULL,
  `materiaPrima_id` INT NOT NULL,
  `pessoa_id` INT NOT NULL,
  `destino_id` INT NOT NULL,
  `Veiculo_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_registroViagens_materiaPrima1_idx` (`materiaPrima_id` ASC) VISIBLE,
  INDEX `fk_registroViagens_pessoa1_idx` (`pessoa_id` ASC) VISIBLE,
  INDEX `fk_registroViagens_endereco1_idx` (`destino_id` ASC) VISIBLE,
  INDEX `fk_registroViagens_Veiculo1_idx` (`Veiculo_id` ASC) VISIBLE,
  CONSTRAINT `fk_registroViagens_materiaPrima1`
    FOREIGN KEY (`materiaPrima_id`)
    REFERENCES `mydb`.`materiaPrima` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_registroViagens_pessoa1`
    FOREIGN KEY (`pessoa_id`)
    REFERENCES `mydb`.`pessoa4` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_registroViagens_endereco1`
    FOREIGN KEY (`destino_id`)
    REFERENCES `mydb`.`endereco4` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_registroViagens_Veiculo1`
    FOREIGN KEY (`Veiculo_id`)
    REFERENCES `mydb`.`Veiculo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
