
@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Container.puml

LAYOUT_WITH_LEGEND()

title  Container

Person(usuario, "Usuário", "O Usuário do sistema agendamento")

System_Boundary(c1, "Sistema de contas") {
    Container(Mobile_app, "Aplicativo Mobile", "C#, Xamarim", "Fornece um conjuto de funcionalidades ao usuários por meio de dispositivos móveis")
    ContainerDb(DataBase, "Banco de dados", "SQL Database", "Armazena as informações do usuário, logi")
}
System(sistema_contas, "Sistema de Contas", "Permite que usuários verifiquem suas informações pessoais")
System_Ext(sistema_notificacao, "Sistema de Notificação", "Sistema responsavel por notificar o usuário")
System(agendamento, "Sistema de Agendamento", "Sistema responsavel por gerenciar os agendamentos")

Rel(usuario, sistema_contas, "Usa")
Rel_Back(usuario, sistema_notificacao, "Envia notificação para")
Rel_Neighbor(agendamento, sistema_notificacao, "Envia notificação")
Rel(sistema_contas, agendamento, "Usa")
@enduml